### ISSUE TITLE
BAGEL 1.2.0 Segmentation fault when running "save_ref"

### ISSUE THREAD

**Issue by yapolyak** [nubakery/bagel#142] opened 2018-11-23 17:31 UTC
Dear developers,

I've built Bagel with intel/2018/3, intel mpi and Boost/1.58. When I am trying to save orbitals, it crashes with a segmentation fault. It happens for any input, e.g.

```
{ "bagel" : [

{
  "title" : "molecule",
  "basis" : "cc-pvdz",
  "df_basis" : "cc-pvdz-jkfit",
  "angstrom" : "true",
  "geometry" : [
   { "atom" : "C", "xyz" : [     -0.086568,     -0.005668,     -0.062005 ] },
   { "atom" : "C", "xyz" : [     -0.011715,     -0.000767,      2.591704 ] },
   { "atom" : "C", "xyz" : [      2.307489,      0.152646,      3.873550 ] },
   { "atom" : "C", "xyz" : [      4.569168,      0.306767,      2.476623 ] },
   { "atom" : "C", "xyz" : [      4.507443,      0.302666,     -0.182638 ] },
   { "atom" : "C", "xyz" : [      2.181787,      0.146118,     -1.440984 ] },
   { "atom" : "N", "xyz" : [      7.016221,      0.475413,      3.596330 ] },
   { "atom" : "N", "xyz" : [      7.095858,      0.456933,      5.951341 ] },
   { "atom" : "N", "xyz" : [      7.443796,      0.458948,      8.119164 ] },
   { "atom" : "H", "xyz" : [     -1.899956,     -0.127115,     -1.048443 ] },
   { "atom" : "H", "xyz" : [     -1.767532,     -0.117817,      3.681025 ] },
   { "atom" : "H", "xyz" : [      2.355709,      0.156880,      5.944419 ] },
   { "atom" : "H", "xyz" : [      6.294144,      0.430773,     -1.215843 ] },
   { "atom" : "H", "xyz" : [      2.143222,      0.143260,     -3.509778 ] }
  ]
},

{
 "title" : "hf"
},

{
 "title" : "mp2",
 "aux_basis" : "cc-pvdz-ri",
 "frozen" : true
},

{
  "title" : "save_ref",
  "file" : "mp2.restart.min"
}

]}
```
Thank you very much in advance for considering my request!

Best wishes,

Iakov

**Comment by yapolyak** [comment] 2018-11-23 17:37
In the above input I should've had "angstrom" : "false", but this doesn't help with respect to the segfault.

**Comment by yapolyak** [comment] 2018-11-25 22:37
If I compile Bagel with GCC7.3 and Boost1.68, there is no segmentation fault, everything runs OK. 

So may be something either with old Boost version or with Intel compiler... Actually, when I try compiling using intel/2018 compiler and Boost1.68, I am getting linking errors, but this might have to do with the way Boost has been built (shouldn't matter though I'd thought as it's headers mainly)...

Have you been successful compiling Bagel with Intel compiler?

**Comment by shiozaki** [comment] 2018-11-26 00:15
I have no access to Intel compilers, but I am aware that many of the users are successfully using Intel Compiler.

Generally speaking, for serialization to work (which is used in save_ref), Boost should be compiled with the same compiler as the one you use for BAGEL. I suspect that Boost in your system was compiled with GCC. Hope this helps.

Since this is not a bug in BAGEL, let me close the issue.

**Closed by shiozaki** 2018-11-26 00:15 UTC

**Comment by yapolyak** [comment] 2018-11-26 09:56
Thank you very much for your answer! 

Kind regards,

Iakov
