### ISSUE TITLE
Z vector equation error constant throughout iterations

### ISSUE THREAD

**Issue by nagb** [nubakery/bagel#208] opened 2020-07-23 10:32 UTC
I don't know if this has come up to any users before but I couldn't find anything while searching through the archive in here.

I am running an MS-CASPT2 optimisation and while the program is going through the gradient stage it gets stuck trying to solve the Z vector equations: 

  === CASSCF Z-vector iteration ===

         0      0.0037950075   151.7911993374      1.64
    - linear dependency detected:    1 /    2    min eigenvalue:     9.6233e-09    max eigenvalue:     9.6233e-09
    * Using canonical orthogonalization due to linear dependency

         1      0.0038000891   151.7911995828      1.46
    - linear dependency detected:    2 /    3    min eigenvalue:    -3.9371e-16    max eigenvalue:     7.1625e-09
    * Using canonical orthogonalization due to linear dependency

         2      0.0038091857   151.7911997637      1.67
    - linear dependency detected:    3 /    4    min eigenvalue:    -2.6138e-16    max eigenvalue:     2.6369e-09
    * Using canonical orthogonalization due to linear dependency

         3      0.0038157240   151.7911997210      1.78
    - linear dependency detected:    4 /    5    min eigenvalue:    -9.5739e-17    max eigenvalue:     5.2881e-09
    * Using canonical orthogonalization due to linear dependency

         4      0.0038124812   151.7911997586      1.62
    - linear dependency detected:    5 /    6    min eigenvalue:    -5.8490e-16    max eigenvalue:     6.2254e-09
    * Using canonical orthogonalization due to linear dependency

         5      0.0038104955   151.7911997658      1.52
    - linear dependency detected:    6 /    7    min eigenvalue:    -2.6349e-16    max eigenvalue:     6.5097e-09
    * Using canonical orthogonalization due to linear dependency

         6      0.0038095331   151.7911997648      1.49
    - linear dependency detected:    7 /    8    min eigenvalue:    -3.1906e-16    max eigenvalue:     6.6177e-09
    * Using canonical orthogonalization due to linear dependency

         7      0.0038090163   151.7911997630      1.48
    - linear dependency detected:    8 /    9    min eigenvalue:    -8.8894e-16    max eigenvalue:     6.6659e-09
    * Using canonical orthogonalization due to linear dependency

         8      0.0038087188   151.7911997616      1.50
    - linear dependency detected:    9 /   10    min eigenvalue:    -2.4152e-15    max eigenvalue:     6.6901e-09
    * Using canonical orthogonalization due to linear dependency

         9      0.0038085355   151.7911997606      1.54
    - linear dependency detected:   10 /   11    min eigenvalue:    -6.2078e-16    max eigenvalue:     6.7035e-09
    * Using canonical orthogonalization due to linear dependency

        10      0.0038084156   151.7911997598      1.50
    - linear dependency detected:   11 /   12    min eigenvalue:    -1.0187e-15    max eigenvalue:     6.7114e-09
    * Using canonical orthogonalization due to linear dependency

        11      0.0038083332   151.7911997593      1.76
    - linear dependency detected:   12 /   13    min eigenvalue:    -1.1373e-15    max eigenvalue:     6.7164e-09
    * Using canonical orthogonalization due to linear dependency

        12      0.0038082743   151.7911997589      1.77
    - linear dependency detected:   13 /   14    min eigenvalue:    -5.9847e-16    max eigenvalue:     6.7196e-09
    * Using canonical orthogonalization due to linear dependency

        13      0.0038082308   151.7911997586      1.56
    - linear dependency detected:   14 /   15    min eigenvalue:    -1.1299e-15    max eigenvalue:     6.7218e-09
    * Using canonical orthogonalization due to linear dependency

        14      0.0038081978   151.7911997584      1.53
    - linear dependency detected:   15 /   16    min eigenvalue:    -2.1309e-15    max eigenvalue:     6.7233e-09
    * Using canonical orthogonalization due to linear dependency

        15      0.0038081722   151.7911997582      1.60
    - linear dependency detected:   16 /   17    min eigenvalue:    -2.7386e-15    max eigenvalue:     6.7244e-09
    * Using canonical orthogonalization due to linear dependency

        16      0.0038081520   151.7911997581      1.88
    - linear dependency detected:   17 /   18    min eigenvalue:    -1.6310e-15    max eigenvalue:     6.7252e-09
    * Using canonical orthogonalization due to linear dependency

        17      0.0038081357   151.7911997579      1.59
    - linear dependency detected:   18 /   19    min eigenvalue:    -2.0190e-15    max eigenvalue:     6.7258e-09
    * Using canonical orthogonalization due to linear dependency

        18      0.0038081225   151.7911997578      1.73
    - linear dependency detected:   19 /   20    min eigenvalue:    -2.1896e-15    max eigenvalue:     6.7263e-09
    * Using canonical orthogonalization due to linear dependency

        19      0.0038081116   151.7911997578      1.58
    - linear dependency detected:   20 /   21    min eigenvalue:    -4.5704e-15    max eigenvalue:     6.7267e-09
    * Using canonical orthogonalization due to linear dependency

        20      0.0038081026   151.7911997577      1.44
    - linear dependency detected:   21 /   22    min eigenvalue:    -4.2884e-15    max eigenvalue:     6.7269e-09
    * Using canonical orthogonalization due to linear dependency

        21      0.0038080949   151.7911997576      1.54
    - linear dependency detected:   22 /   23    min eigenvalue:    -1.3493e-15    max eigenvalue:     6.7272e-09
    * Using canonical orthogonalization due to linear dependency

        22      0.0038080884   151.7911997576      1.50
    - linear dependency detected:   23 /   24    min eigenvalue:    -1.4167e-15    max eigenvalue:     6.7273e-09
    * Using canonical orthogonalization due to linear dependency

        23      0.0038080829   151.7911997576      1.45
    - linear dependency detected:   24 /   25    min eigenvalue:    -1.2044e-15    max eigenvalue:     6.7275e-09
    * Using canonical orthogonalization due to linear dependency

        24      0.0038080781   151.7911997575      1.44
    - linear dependency detected:   25 /   26    min eigenvalue:    -1.4839e-15    max eigenvalue:     6.7276e-09
    * Using canonical orthogonalization due to linear dependency

        25      0.0038080740   151.7911997575      1.45
    - linear dependency detected:   26 /   27    min eigenvalue:    -6.0602e-15    max eigenvalue:     6.7277e-09
    * Using canonical orthogonalization due to linear dependency

        26      0.0038080703   151.7911997575      1.52
    - linear dependency detected:   27 /   28    min eigenvalue:    -1.2136e-15    max eigenvalue:     6.7278e-09
    * Using canonical orthogonalization due to linear dependency

        27      0.0038080672   151.7911997574      1.48
    - linear dependency detected:   28 /   29    min eigenvalue:    -3.5270e-15    max eigenvalue:     6.7278e-09
    * Using canonical orthogonalization due to linear dependency

        28      0.0038080644   151.7911997574      1.53
    - linear dependency detected:   29 /   30    min eigenvalue:    -1.6051e-15    max eigenvalue:     6.7279e-09
    * Using canonical orthogonalization due to linear dependency

        29      0.0038080619   151.7911997574      1.43
    - linear dependency detected:   30 /   31    min eigenvalue:    -3.2801e-15    max eigenvalue:     6.7280e-09
    * Using canonical orthogonalization due to linear dependency

        30      0.0038080597   151.7911997574      1.51
    - linear dependency detected:   31 /   32    min eigenvalue:    -1.3774e-15    max eigenvalue:     6.7280e-09
    * Using canonical orthogonalization due to linear dependency

        31      0.0038080577   151.7911997574      1.42
    - linear dependency detected:   32 /   33    min eigenvalue:    -3.3450e-15    max eigenvalue:     6.7280e-09
    * Using canonical orthogonalization due to linear dependency

        32      0.0038080559   151.7911997574      1.46
    - linear dependency detected:   33 /   34    min eigenvalue:    -3.8668e-15    max eigenvalue:     6.7281e-09
    * Using canonical orthogonalization due to linear dependency

        33      0.0038080544   151.7911997573      1.45
    - linear dependency detected:   34 /   35    min eigenvalue:    -7.9658e-15    max eigenvalue:     6.7281e-09
    * Using canonical orthogonalization due to linear dependency

        34      0.0038080529   151.7911997573      1.46
    - linear dependency detected:   35 /   36    min eigenvalue:    -6.5164e-15    max eigenvalue:     6.7281e-09
    * Using canonical orthogonalization due to linear dependency

        35      0.0038080516   151.7911997573      1.46
    - linear dependency detected:   36 /   37    min eigenvalue:    -5.4920e-15    max eigenvalue:     6.7281e-09
    * Using canonical orthogonalization due to linear dependency

        36      0.0038080504   151.7911997573      1.45
    - linear dependency detected:   37 /   38    min eigenvalue:    -7.4559e-15    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        37      0.0038080494   151.7911997573      1.46
    - linear dependency detected:   38 /   39    min eigenvalue:    -8.6966e-15    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        38      0.0038080484   151.7911997573      1.43
    - linear dependency detected:   39 /   40    min eigenvalue:    -6.3043e-15    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        39      0.0038080475   151.7911997573      1.42
    - linear dependency detected:   40 /   41    min eigenvalue:    -1.0500e-14    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        40      0.0038080467   151.7911997573      1.44
    - linear dependency detected:   41 /   42    min eigenvalue:    -5.6837e-15    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        41      0.0038080459   151.7911997573      1.47
    - linear dependency detected:   42 /   43    min eigenvalue:    -6.0721e-15    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        42      0.0038080452   151.7911997573      1.48
    - linear dependency detected:   43 /   44    min eigenvalue:    -1.0127e-14    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        43      0.0038080446   151.7911997573      1.48
    - linear dependency detected:   44 /   45    min eigenvalue:    -1.0155e-14    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        44      0.0038080440   151.7911997573      1.64
    - linear dependency detected:   45 /   46    min eigenvalue:    -8.2939e-15    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        45      0.0038080434   151.7911997573      1.55
    - linear dependency detected:   46 /   47    min eigenvalue:    -6.5684e-15    max eigenvalue:     6.7282e-09
    * Using canonical orthogonalization due to linear dependency

        46      0.0038080429   151.7911997573      1.54
    - linear dependency detected:   47 /   48    min eigenvalue:    -8.6369e-15    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        47      0.0038080424   151.7911997572      1.48
    - linear dependency detected:   48 /   49    min eigenvalue:    -9.7886e-15    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        48      0.0038080420   151.7911997572      1.45
    - linear dependency detected:   49 /   50    min eigenvalue:    -1.2269e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        49      0.0038080416   151.7911997572      1.46
    - linear dependency detected:   50 /   51    min eigenvalue:    -9.3614e-15    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        50      0.0038080412   151.7911997572      1.45
    - linear dependency detected:   51 /   52    min eigenvalue:    -1.3487e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        51      0.0038080408   151.7911997572      1.54
    - linear dependency detected:   52 /   53    min eigenvalue:    -1.1798e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        52      0.0038080405   151.7911997572      1.50
    - linear dependency detected:   53 /   54    min eigenvalue:    -1.0188e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        53      0.0038080402   151.7911997572      1.51
    - linear dependency detected:   54 /   55    min eigenvalue:    -9.5212e-15    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        54      0.0038080399   151.7911997572      1.49
    - linear dependency detected:   55 /   56    min eigenvalue:    -8.1243e-15    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        55      0.0038080396   151.7911997572      1.48
    - linear dependency detected:   56 /   57    min eigenvalue:    -1.2907e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        56      0.0038080393   151.7911997572      1.48
    - linear dependency detected:   57 /   58    min eigenvalue:    -9.0228e-15    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        57      0.0038080391   151.7911997572      1.45
    - linear dependency detected:   58 /   59    min eigenvalue:    -1.0106e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        58      0.0038080388   151.7911997572      1.48
    - linear dependency detected:   59 /   60    min eigenvalue:    -1.1162e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        59      0.0038080386   151.7911997572      1.49
    - linear dependency detected:   60 /   61    min eigenvalue:    -1.1221e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        60      0.0038080384   151.7911997572      1.46
    - linear dependency detected:   61 /   62    min eigenvalue:    -1.0833e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        61      0.0038080382   151.7911997572      1.47
    - linear dependency detected:   62 /   63    min eigenvalue:    -9.5992e-15    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        62      0.0038080380   151.7911997572      1.45
    - linear dependency detected:   63 /   64    min eigenvalue:    -1.8595e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        63      0.0038080378   151.7911997572      1.46
    - linear dependency detected:   64 /   65    min eigenvalue:    -1.2941e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        64      0.0038080377   151.7911997572      1.48
    - linear dependency detected:   65 /   66    min eigenvalue:    -1.5033e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        65      0.0038080375   151.7911997572      1.50
    - linear dependency detected:   66 /   67    min eigenvalue:    -1.5957e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        66      0.0038080374   151.7911997572      1.51
    - linear dependency detected:   67 /   68    min eigenvalue:    -1.2695e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        67      0.0038080372   151.7911997572      1.47
    - linear dependency detected:   68 /   69    min eigenvalue:    -1.6423e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        68      0.0038080371   151.7911997572      1.48
    - linear dependency detected:   69 /   70    min eigenvalue:    -1.2264e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        69      0.0038080369   151.7911997572      1.47
    - linear dependency detected:   70 /   71    min eigenvalue:    -1.7973e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        70      0.0038080368   151.7911997572      1.49
    - linear dependency detected:   71 /   72    min eigenvalue:    -1.7339e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        71      0.0038080367   151.7911997572      1.50
    - linear dependency detected:   72 /   73    min eigenvalue:    -1.3457e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        72      0.0038080366   151.7911997572      1.49
    - linear dependency detected:   73 /   74    min eigenvalue:    -1.4050e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        73      0.0038080365   151.7911997572      1.51
    - linear dependency detected:   74 /   75    min eigenvalue:    -1.7381e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        74      0.0038080364   151.7911997572      1.47
    - linear dependency detected:   75 /   76    min eigenvalue:    -1.5687e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        75      0.0038080363   151.7911997572      1.47
    - linear dependency detected:   76 /   77    min eigenvalue:    -1.3622e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        76      0.0038080362   151.7911997572      1.48
    - linear dependency detected:   77 /   78    min eigenvalue:    -9.9842e-15    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        77      0.0038080361   151.7911997572      1.46
    - linear dependency detected:   78 /   79    min eigenvalue:    -1.3477e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        78      0.0038080360   151.7911997572      1.48
    - linear dependency detected:   79 /   80    min eigenvalue:    -1.2744e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        79      0.0038080359   151.7911997572      1.48
    - linear dependency detected:   80 /   81    min eigenvalue:    -1.7111e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        80      0.0038080358   151.7911997572      1.48
    - linear dependency detected:   81 /   82    min eigenvalue:    -1.6368e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        81      0.0038080358   151.7911997572      1.48
    - linear dependency detected:   82 /   83    min eigenvalue:    -2.0525e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        82      0.0038080357   151.7911997572      1.50
    - linear dependency detected:   83 /   84    min eigenvalue:    -1.6045e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        83      0.0038080356   151.7911997572      1.49
    - linear dependency detected:   84 /   85    min eigenvalue:    -1.7029e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        84      0.0038080356   151.7911997572      1.52
    - linear dependency detected:   85 /   86    min eigenvalue:    -1.2104e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        85      0.0038080355   151.7911997572      1.49
    - linear dependency detected:   86 /   87    min eigenvalue:    -2.0542e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        86      0.0038080354   151.7911997572      1.46
    - linear dependency detected:   87 /   88    min eigenvalue:    -2.0156e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        87      0.0038080354   151.7911997572      1.47
    - linear dependency detected:   88 /   89    min eigenvalue:    -1.5512e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        88      0.0038080353   151.7911997572      1.46
    - linear dependency detected:   89 /   90    min eigenvalue:    -1.5183e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        89      0.0038080352   151.7911997572      1.50
    - linear dependency detected:   90 /   91    min eigenvalue:    -2.2305e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        90      0.0038080352   151.7911997572      1.50
    - linear dependency detected:   91 /   92    min eigenvalue:    -1.8628e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        91      0.0038080351   151.7911997572      1.46
    - linear dependency detected:   92 /   93    min eigenvalue:    -1.7681e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        92      0.0038080351   151.7911997572      1.49
    - linear dependency detected:   93 /   94    min eigenvalue:    -2.5890e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        93      0.0038080350   151.7911997572      1.46
    - linear dependency detected:   94 /   95    min eigenvalue:    -1.5689e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        94      0.0038080350   151.7911997572      1.46
    - linear dependency detected:   95 /   96    min eigenvalue:    -2.3585e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        95      0.0038080350   151.7911997572      1.48
    - linear dependency detected:   96 /   97    min eigenvalue:    -1.6829e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        96      0.0038080349   151.7911997572      1.45
    - linear dependency detected:   97 /   98    min eigenvalue:    -1.7934e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        97      0.0038080349   151.7911997572      1.48
    - linear dependency detected:   98 /   99    min eigenvalue:    -1.9011e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        98      0.0038080348   151.7911997572      1.46
    - linear dependency detected:   99 /  100    min eigenvalue:    -2.1200e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

        99      0.0038080348   151.7911997572      1.49
    - linear dependency detected:  100 /  101    min eigenvalue:    -2.3650e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

       100      0.0038080347   151.7911997572      1.49
    - linear dependency detected:  101 /  102    min eigenvalue:    -1.7909e-14    max eigenvalue:     6.7283e-09
    * Using canonical orthogonalization due to linear dependency

Then the program moves on to the next geometry and a bad gradient keeps getting calculated for the following steps.

I've found that this pattern is dependent on the "thresh_overlap" parameter. Sometimes these errors go away with a loose value such as 1e-4 but then they resurge at a later geometry.

Does anyone know what may be going on here?

Regards,
Nuno

**Comment by shiozaki** [comment] 2020-07-23 12:05
Please use XMS-CASPT2. MS-CASPT2 is an ill defined theory and that’s
reflected in the instability of the Z vector equation. For theoretical
backgrounds, read Granovsky 2011 JCP and perhaps some of mine.

**Comment by nagb** [comment] 2020-07-23 13:20
Thanks for commenting. 

I will try the XMS variant but I was under the impression that XMS-CASPT2 is not so good for excited state energies (Lindh et al  https://dx.doi.org/10.1021/acs.jctc.9b01129) hence my hesitation. 

Full disclosure I am also using a non-standard imaginary shift of 0.5 au since from a OpenMOLCAS single point run I see some intruder states. In BAGEL I don't know how to spot them.

**Comment by shiozaki** [comment] 2020-07-23 13:54
The usefulness of XMS-CASPT2 has been established so I don't intend to argue here (for that matter, I don't agree with Roland, except when you are studying very high lying state (like 30th excited state)). In any event, the deficiency of MS-CASPT2 Z vector cannot be fixed because the problem lies in the MS-CASPT2 parameterization.

On a separate note, likely, there are multiple sources of intruders. MOLCAS has more sources of intruders than BAGEL does; so it may be that an imaginary shift of 0.5 is not necessary. But you never know. Just calculate something with different shifts and see how it behaves. The same amount of information as Molcas is printed out in BAGEL.

Since I am not in academia any longer, I have no time to help you with specific input files, but hope this helps. I will close the issue.

PS: When XMS-CAPST2 vs MS-CASPT2 accuracy is the issue, it means that CASPT2 ansaz itself is not sufficient, so you better do something other than CASPT2.

PPS: I think the cause of slow adaptation of XMS-CASPT2 is because it was proposed by Granovsky in Russian who didn't travel to the western world (he passed away last year), and because Molcas is not setup to implement XMS-CASPT2 correctly (they use a state-specific Fock operator instead of state averaged one.

**Closed by shiozaki** 2020-07-23 13:54 UTC

**Comment by nagb** [comment] 2020-07-23 14:01
Thank you very much for those insightful comments! 
I will take these into consideration when I run more trials.

**Comment by nagb** [comment] 2020-07-24 13:25
Just as a follow-up, I can confirm that the Z-vector equations with XMS-CASPT2 is numerically stable for my system and the optimisation goes smoothly.

**Comment by shiozaki** [comment] 2020-07-24 13:47
Cool, thanks for letting me know.
