### ISSUE TITLE
molden import fails when dkh is present

### ISSUE THREAD

**Issue by jesusG-V** [nubakery/bagel#150] opened 2019-02-02 00:39 UTC
It looks that it is not possible to use a molden file and the dkh Hamiltonian at the same time. Attached you can find an example
[hf_svp_dfhf_dkh_grad.zip](https://github.com/nubakery/bagel/files/2823815/hf_svp_dfhf_dkh_grad.zip)

When I send the test hf_svp_dfhf_dkh_grad adding a print, it works fine... but it is not possible to redo the calculation reading the created molden file

**Comment by shiozaki** [comment] 2019-02-05 18:47
Jesus - strage ... I cannot reproduce the error (it runs through to completion, giving the right gradient). Are you using the latest master?

```
{shiozaki@pro src}$ cat test2.json
{ "bagel" : [

{
 "title" : "molecule",
 "basis" : "molden",
 "dkh" : true,
 "df_basis" : "svp-jkfit",
 "molden_file" : "guess.molden"
},

{
  "title" : "force",
  "method" : [ {
    "title" : "hf",
    "thresh" : 1.0e-10
  } ]
}

]}
```

and 

```
{shiozaki@pro src}$ ./BAGEL  test2.json 
  * using 8 threads per process

  ===============================================================
    BAGEL - Freshly leavened quantum chemistry                   
  ===============================================================

  *** Geometry ***

  { "atom" : "F", "xyz" : [     -0.000000,     -0.000000,      2.720616 ] },
  { "atom" : "H", "xyz" : [     -0.000000,     -0.000000,      0.305956 ] },

  Number of auxiliary basis functions:       95

  Since a DF basis is specified, we compute 2- and 3-index integrals:
    o Being stored without compression. Storage requirement is 0.000 GB
       - 3-index ints prep                         0.00
       - 3-index ints                              0.03
       - 2-index ints                              0.00
       - computing inverse                         0.03
        elapsed time:        0.05 sec.


  Number of basis functions:       19
  Number of electrons      :       10


    * METHOD: MOLECULE                             0.13

  The gradients will be computed analytically.
       - Overlap matrix                            0.00
       - Hcore matrix                              0.01
       - Overlap orthog                            0.00

  *** RHF ***

  === Nuclear Repulsion ===
  
     3.7272328195

      * DIIS with orbital gradients will be used.

       - SCF startup                               0.00

  === RHF iteration (molden) ===
  
      0        -99.92869677          0.00000000           0.00
  
    * SCF iteration converged.

    * Permanent dipole moment:
           (    0.000000,    -0.000000,     1.049897) a.u.


  * Nuclear energy gradient

    o Atom   0
        x         -0.0000000000
        y          0.0000000000
        z          0.1590879598
    o Atom   1
        x          0.0000000000
        y         -0.0000000000
        z         -0.1590879598
  * Gradient computed with                              0.06


    * METHOD: FORCE                                0.08


  
  ===============================================================
```

**Comment by shiozaki** [comment] 2019-02-06 17:04
I will close this issue tentatively - if the problem persists, please reopen with additional information. Thanks!

**Closed by shiozaki** 2019-02-06 17:04 UTC
