### ISSUE TITLE
Could not find a version of the Boost::Regex library!

### ISSUE THREAD

**Issue by miroi** [nubakery/bagel#162] opened 2019-07-01 14:06 UTC
Hello,

I want to compile BAGEL on our cluster, however, there is some issue with boost library, see below.
Any help please ?

~~~
milias@lxbk0196.gsi.de:/lustre/nyx/ukt/milias/work/software/bagel/bagel_master/../configure --prefix=/lustre/nyx/ukt/milias/work/software/bagel
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=c++11... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking how to convert x86_64-unknown-linux-gnu file names to x86_64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for mt... mt
checking if mt is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... g++ -E
checking for ld used by g++... /usr/bin/ld -m elf_x86_64
checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC -DPIC
checking if g++ PIC flag -fPIC -DPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking if g++ supports -c -o file.o... (cached) yes
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for boostlib >= 1.53... yes
checking whether the Boost::Regex library is available... yes
configure: error: Could not find a version of the Boost::Regex library!
milias@lxbk0196.gsi.de:/lustre/nyx/ukt/milias/work/software/bagel/bagel_master/.
~~~

**Comment by shiozaki** [comment] 2019-07-01 14:14
Hi would you be able to share configure options and config.log? Also "ls" of the boost directory that you specified.

Toru

**Comment by miroi** [comment] 2019-07-01 14:18
Hello,

the config log file is attached,
[config.log](https://github.com/nubakery/bagel/files/3346003/config.log)

but I did not specify Boost library in configure parameter ... I used the default. How do I check the presence of Boost library on a cluster, please ?

**Comment by shiozaki** [comment] 2019-07-01 14:21
Since it does not pick it up, it is not in a standard location. Please ask your computer administrator. If there isn't, it's easy to compile. Just download and unzip, and
```
./bootstrap.sh
./b2 -j8 --prefix=/usr/local
sudo ./b2 install
```

**Comment by miroi** [comment] 2019-07-01 14:23
OK, I will try. 
I thought boost was already there based on the output:
~~~
.
checking for boostlib >= 1.53... yes
checking whether the Boost::Regex library is available... yes
configure: error: Could not find a version of the Boost::Regex library!
~~~

**Comment by shiozaki** [comment] 2019-07-01 14:26
Maybe and maybe not. You should specify --with-boost. Otherwise the result is all dependent on your environmental variables, which is impossible to reproduce.

**Comment by miroi** [comment] 2019-07-01 15:43
Well, still the same error from configure:
~~~
milias@lxbk0196.gsi.de:/lustre/nyx/ukt/milias/work/software/bagel/bagel_master/../configure --prefix=$PWD --with-boost=/lustre/nyx/ukt/milias/wok/software/boost-lib/boost_1_70_0  --with-boost-regex
.
.
.
checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking dynamic linker characteristics... (cached) GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking for boostlib >= 1.53... yes
checking whether the Boost::Regex library is available... yes
configure: error: Could not find a version of the Boost::Regex library!
~~~

I installed Boost, but what is Boost-regex ? New library?

**Comment by shiozaki** [comment] 2019-07-01 15:57
No it’s a standard part of boost. It’s not a problem on the bagel side.

**Comment by miroi** [comment] 2019-07-01 16:35
well, I installled fresh boost, provided links, but is the configure script  up to date ?
~~~
milias@lxbk0196.gsi.de:/lustre/nyx/ukt/milias/work/software/bagel/bagel_master/../configure -V
BAGEL configure 1.2.0
generated by GNU Autoconf 2.69
~~~

Isn't there a simpler way to build bagel without these scripts ?

**Comment by shiozaki** [comment] 2019-07-01 16:36
No. Please follow the instruction on the website every step by step. Toru

**Comment by shiozaki** [comment] 2019-07-05 06:45
This is a boost build/linking problem, and therefore, I will close this issue. The installation of BOOST can be checked by linking boost with a test program that contains only a main function.

**Closed by shiozaki** 2019-07-05 06:45 UTC

**Comment by miroi** [comment] 2019-08-06 09:53
OK, I found solution for boost, based on https://stackoverflow.com/a/19796701/3101910,
~~~
milias@lxir127.gsi.de:/tmp/milias-work/software/qch/bagel/bagel_master/.FC=ifort CC=icc CXX=icpc  ./configure  --prefix=/tmp/milias-work/software/qch/bagel/bagel_master/build_intel17_mkl  --with-boost=yes --with-boost-libdir=/usr/lib/x86_64-linux-gnu
~~~

**Comment by vamshimohank** [comment] 2019-10-02 05:40
I too had the same issue and the solution suggested by @miroi has helped. Thanks @miroi. 
@shiozaki Perhaps it is a good idea to put it somewhere in the FAQ list or common problems list to help others who might have the same issue. 

Regards
Vamshi

**Comment by shiozaki** [comment] 2019-10-07 14:48
I think it's already sufficiently documented. Do
```
../configure --help
```
