### ISSUE TITLE
configure bagel.1.1.1 error: C compiler cannot create executables

### ISSUE THREAD

**Issue by aerask** [nubakery/bagel#124] opened 2018-08-01 03:36 UTC
Dear developers,

I’m trying to install bagel.1.1.1 with boost.1.64, autotools.2.69, and gcc.4.9.4 but I’m hitting an error I believe is due to autoconf trying to compile boost’s include directory rather than boost itself (bolded) resulting in the C compiler being unable to create executables (also bolded). This was tried with both the tar.gz and github clone routes for the newest version of BAGEL and both produced the same error. Given this, could the problem be due to a missing library and/or perhaps a different version of autotools?

**Configure process:**
$ export BOOST_ROOT=/export/apps/Boost/1.64.0/
$ export LD_LIBRARY_PATH=$BOOST_ROOT/lib:$LD_LIBRARY_PATH
$ ../configure --enable-mkl --with-boost=$BOOST_ROOT --with-mpi=intel

**Printout after configuring:**
configure: WARNING: unrecognized options: --with-boost
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for python... /usr/bin/python
checking for python version... 2.6
checking for python platform... linux2
checking for python script directory... ${prefix}/lib/python2.6/site-packages
checking for python extension module directory... ${exec_prefix}/lib64/python2.6/site-packages
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/export/zimmerman/aerask/bagel/obj':
configure: error: **C compiler cannot create executables**
See `config.log' for more details

**Following configure.log core tests readout:**
configure:2440: checking for a BSD-compatible install
configure:2508: result: /usr/bin/install -c
configure:2519: checking whether build environment is sane
configure:2569: result: yes
configure:2710: checking for a thread-safe mkdir -p
configure:2749: result: /bin/mkdir -p
configure:2762: checking for gawk
configure:2778: found /bin/gawk
configure:2789: result: gawk
configure:2800: checking whether make sets $(MAKE)
configure:2822: result: yes
configure:2912: checking for python
configure:2930: found /usr/bin/python
configure:2942: result: /usr/bin/python
configure:2963: checking for python version
configure:2970: result: 2.6
configure:2982: checking for python platform
configure:2989: result: linux2
configure:2996: checking for python script directory
configure:3025: result: ${prefix}/lib/python2.6/site-packages
configure:3034: checking for python extension module directory
configure:3063: result: ${exec_prefix}/lib64/python2.6/site-packages
configure:3147: checking for gcc
configure:3163: found /export/apps/GCC/4.9.4/bin//gcc
configure:3174: result: gcc
configure:3205: checking for C compiler version
configure:3214: gcc --version >&5
gcc (GCC) 4.9.4
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3225: $? = 0
configure:3214: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/export/apps/GCC/4.9.4/libexec/gcc/x86_64-unknown-linux-gnu/4.9.4/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ./configure --prefix=/export/apps/GCC/4.9.4 --disable-multilib --enable-languages=c,c++,fortran
Thread model: posix
gcc version 4.9.4 (GCC) 
configure:3225: $? = 0
configure:3214: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3225: $? = 1
configure:3214: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3225: $? = 1
configure:3245: checking whether the C compiler works
**configure:3267: gcc  /export/apps/Boost/1.64.0/include  conftest.c  >&5**
**/export/apps/Boost/1.64.0/include: file not recognized: Is a directory**
collect2: error: ld returned 1 exit status
configure:3271: $? = 1
configure:3309: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "BAGEL"
| #define PACKAGE_TARNAME "bagel"
| #define PACKAGE_VERSION "1.1.1"
| #define PACKAGE_STRING "BAGEL 1.1.1"
| #define PACKAGE_BUGREPORT "shiozaki@northwestern.edu"
| #define PACKAGE_URL "http://www.nubakery.org"
| #define PACKAGE "bagel"
| #define VERSION "1.1.1"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3314: error: in `/export/zimmerman/aerask/bagel/obj':
configure:3316: error: **C compiler cannot create executables**
See `config.log' for more details

**Comment by shiozaki** [comment] 2018-08-01 05:28
Hi Alan,

Sorry for this - this is due to the fact that the manual is ahead of the release (the manual is automatically synchronized with the head of the master branch). We have changed the way the BOOST path is specified recently (May 21st), which occurred after the 1.1.1 release (Feb 22). Can you download the current master branch and try again? Use this link: 
https://github.com/nubakery/bagel/archive/master.zip

Thanks,
Toru

**Comment by shiozaki** [comment] 2018-08-01 05:40
Also I created v1.1.2, which is the latest master head.

**Comment by aerask** [comment] 2018-08-01 20:50
Our system admin here tried both of those approaches out and both gave similar results to above. Using the zip file, error is below. He thinks it's possibly due to icc missing a -I, -l, or -L and treating boost as a source file rather than an include directory (final bolded below). Would you be able to do a fresh compile and send a printout of what the output (console and config.log) is supposed to look like?

**From autoconf:**
aclocal.m4:1037: _LT_SYS_MODULE_PATH_AIX is expanded from...
aclocal.m4:5354: _LT_LANG_CXX_CONFIG is expanded from...
aclocal.m4:800: _LT_LANG is expanded from...
aclocal.m4:783: LT_LANG is expanded from...
aclocal.m4:811: _LT_LANG_DEFAULT_CONFIG is expanded from...
aclocal.m4:159: _LT_SETUP is expanded from...
aclocal.m4:88: LT_INIT is expanded from...
configure.ac:39: the top level
**configure.ac:28: error: possibly undefined macro: AC_MSG_ERROR**
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.

**From configure:**
-bash-4.1$  ../configure --enable-mkl --with-boost=$BOOST_ROOT
--with-mpi=openmpi
**configure: WARNING: unrecognized options: --with-boost**
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for python... /usr/bin/python
checking for python version... 2.6
checking for python platform... linux2
checking for python script directory...
${prefix}/lib/python2.6/site-packages
checking for python extension module directory...
${exec_prefix}/lib64/python2.6/site-packages
checking whether the C compiler works... no
configure: error: in `/home/dave/src/bagel/bagel-master/obj':
configure: error: C compiler cannot create executables
See `config.log' for more details
-bash-4.1$

**From config.log:**
configure:3406: icc -qversion >&5
icc: command line warning #10006: ignoring unknown option '-qversion'
icc: command line error: no files specified; for help type "icc -help"
configure:3417: $? = 1
configure:3437: checking whether the C compiler works
**configure:3459: icc  /export/apps/Boost/1.64.0/include  conftest.c  >&5**
/export/apps/Boost/1.64.0/include: file not recognized: Is a directory
configure:3463: $? = 1
configure:3501: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "BAGEL"
| #define PACKAGE_TARNAME "bagel"
| #define PACKAGE_VERSION "1.1.1"
| #define PACKAGE_STRING "BAGEL 1.1.1"
| #define PACKAGE_BUGREPORT "shiozaki@northwestern.edu"
| #define PACKAGE_URL "http://www.nubakery.org"
| #define PACKAGE "bagel"
| #define VERSION "1.1.1"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3506: error: in `/home/dave/src/bagel/bagel-master/obj':
configure:3508: error: C compiler cannot create executables
See `config.log' for more details

**Comment by shiozaki** [comment] 2018-08-01 20:56
Fresh from the link above.

```
{shiozaki@pro obj}$ export BOOST_ROOT=/usr/local
{shiozaki@pro obj}$ ../configure --with-boost=$BOOST_ROOT --with-mpi=mpich
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ../install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... darwin
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/local/bin/gcc accepts -g... yes
checking for /opt/local/bin/gcc option to accept ISO C89... none needed
checking whether /opt/local/bin/gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of /opt/local/bin/gcc... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether /opt/local/bin/g++ accepts -g... yes
checking dependency style of /opt/local/bin/g++... gcc3
configure: error: "Please specify MPI implementation (openmpi, intel, mvapich)"
{shiozaki@pro obj}$ ../configure --with-boost=$BOOST_ROOT --with-mpi=mvapich
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ../install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... darwin
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/local/bin/gcc accepts -g... yes
checking for /opt/local/bin/gcc option to accept ISO C89... none needed
checking whether /opt/local/bin/gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of /opt/local/bin/gcc... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether /opt/local/bin/g++ accepts -g... yes
checking dependency style of /opt/local/bin/g++... gcc3
..mvapich requested..
checking for mpicc... mpicc
checking for mpicxx... mpicxx
checking whether we are using the GNU C compiler... (cached) yes
checking whether mpicc accepts -g... (cached) yes
checking for mpicc option to accept ISO C89... (cached) none needed
checking whether mpicc understands -c and -o together... (cached) yes
checking dependency style of mpicc... (cached) gcc3
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether mpicxx accepts -g... (cached) yes
checking dependency style of mpicxx... (cached) gcc3
checking whether mpicxx supports C++11 features by default... yes
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by mpicc... /opt/local/bin/ld
checking if the linker (/opt/local/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /opt/local/bin/nm -B
checking the name lister (/opt/local/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin15.6.0 file names to x86_64-apple-darwin15.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.6.0 file names to toolchain format... func_convert_file_noop
checking for /opt/local/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /opt/local/bin/nm -B output from mpicc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... mpicc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if mpicc supports -fno-rtti -fno-exceptions... no
checking for mpicc option to produce PIC... -fno-common -DPIC
checking if mpicc PIC flag -fno-common -DPIC works... yes
checking if mpicc static flag -static works... no
checking if mpicc supports -c -o file.o... yes
checking if mpicc supports -c -o file.o... (cached) yes
checking whether the mpicc linker (/opt/local/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... mpicxx -E
checking for ld used by mpicxx... /opt/local/bin/ld
checking if the linker (/opt/local/bin/ld) is GNU ld... no
checking whether the mpicxx linker (/opt/local/bin/ld) supports shared libraries... yes
checking for mpicxx option to produce PIC... -fno-common -DPIC
checking if mpicxx PIC flag -fno-common -DPIC works... yes
checking if mpicxx static flag -static works... no
checking if mpicxx supports -c -o file.o... yes
checking if mpicxx supports -c -o file.o... (cached) yes
checking whether the mpicxx linker (/opt/local/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for main in -lscalapack... no
configure: error: "Linking against scalapack library failed."
{shiozaki@pro obj}$ ../configure --with-boost=$BOOST_ROOT --with-mpi=mvapich --disable-scalapack
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ../install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for python... /usr/bin/python
checking for python version... 2.7
checking for python platform... darwin
checking for python script directory... ${prefix}/lib/python2.7/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python2.7/site-packages
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /opt/local/bin/gcc accepts -g... yes
checking for /opt/local/bin/gcc option to accept ISO C89... none needed
checking whether /opt/local/bin/gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of /opt/local/bin/gcc... gcc3
checking whether we are using the GNU C++ compiler... yes
checking whether /opt/local/bin/g++ accepts -g... yes
checking dependency style of /opt/local/bin/g++... gcc3
..mvapich requested..
checking for mpicc... mpicc
checking for mpicxx... mpicxx
checking whether we are using the GNU C compiler... (cached) yes
checking whether mpicc accepts -g... (cached) yes
checking for mpicc option to accept ISO C89... (cached) none needed
checking whether mpicc understands -c and -o together... (cached) yes
checking dependency style of mpicc... (cached) gcc3
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether mpicxx accepts -g... (cached) yes
checking dependency style of mpicxx... (cached) gcc3
checking whether mpicxx supports C++11 features by default... yes
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by mpicc... /opt/local/bin/ld
checking if the linker (/opt/local/bin/ld) is GNU ld... no
checking for BSD- or MS-compatible name lister (nm)... /opt/local/bin/nm -B
checking the name lister (/opt/local/bin/nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 196608
checking how to convert x86_64-apple-darwin15.6.0 file names to x86_64-apple-darwin15.6.0 format... func_convert_file_noop
checking how to convert x86_64-apple-darwin15.6.0 file names to toolchain format... func_convert_file_noop
checking for /opt/local/bin/ld option to reload object files... -r
checking for objdump... no
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /opt/local/bin/nm -B output from mpicc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking how to run the C preprocessor... mpicc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if mpicc supports -fno-rtti -fno-exceptions... no
checking for mpicc option to produce PIC... -fno-common -DPIC
checking if mpicc PIC flag -fno-common -DPIC works... yes
checking if mpicc static flag -static works... no
checking if mpicc supports -c -o file.o... yes
checking if mpicc supports -c -o file.o... (cached) yes
checking whether the mpicc linker (/opt/local/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking how to run the C++ preprocessor... mpicxx -E
checking for ld used by mpicxx... /opt/local/bin/ld
checking if the linker (/opt/local/bin/ld) is GNU ld... no
checking whether the mpicxx linker (/opt/local/bin/ld) supports shared libraries... yes
checking for mpicxx option to produce PIC... -fno-common -DPIC
checking if mpicxx PIC flag -fno-common -DPIC works... yes
checking if mpicxx static flag -static works... no
checking if mpicxx supports -c -o file.o... yes
checking if mpicxx supports -c -o file.o... (cached) yes
checking whether the mpicxx linker (/opt/local/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin15.6.0 dyld
checking how to hardcode library paths into programs... immediate
checking for boostlib >= 1.53... yes
checking whether the Boost::Regex library is available... yes
checking for exit in -lboost_regex... yes
checking whether the Boost::Unit_Test_Framework library is available... yes
configure: WARNING: BOOST_CPPFLAGS -I/usr/local/include
checking whether the Boost::Serialization library is available... yes
checking for exit in -lboost_serialization... yes
checking for zgemm3m_... no
checking mpi.h usability... yes
checking mpi.h presence... yes
checking for mpi.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating src/util/Makefile
config.status: creating src/util/input/Makefile
config.status: creating src/util/io/Makefile
config.status: creating src/util/parallel/Makefile
config.status: creating src/util/math/Makefile
config.status: creating src/asd/multisite/Makefile
config.status: creating src/asd/dimer/Makefile
config.status: creating src/asd/dmrg/Makefile
config.status: creating src/asd/orbital/Makefile
config.status: creating src/asd/Makefile
config.status: creating src/wfn/Makefile
config.status: creating src/grad/Makefile
config.status: creating src/integral/Makefile
config.status: creating src/scf/Makefile
config.status: creating src/df/Makefile
config.status: creating src/prop/Makefile
config.status: creating src/smith/Makefile
config.status: creating src/molecule/Makefile
config.status: creating src/pt2/Makefile
config.status: creating src/ci/Makefile
config.status: creating src/ci/ciutil/Makefile
config.status: creating src/ci/fci/Makefile
config.status: creating src/ci/zfci/Makefile
config.status: creating src/ci/ras/Makefile
config.status: creating src/response/Makefile
config.status: creating src/multi/Makefile
config.status: creating src/multi/casscf/Makefile
config.status: creating src/multi/zcasscf/Makefile
config.status: creating src/mat1e/Makefile
config.status: creating src/periodic/Makefile
config.status: creating src/opt/Makefile
config.status: creating src/basis/Makefile
config.status: creating bagel_config.h
config.status: executing depfiles commands
config.status: executing lib tool commands
```

**Comment by shiozaki** [comment] 2018-08-01 20:58
What is your autoconf version? Mine is
```
{shiozaki@pro obj}$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.
```

**Comment by shiozaki** [comment] 2018-08-01 20:59
You are missing a package.
https://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error

I will close the issue.

**Comment by shiozaki** [comment] 2018-08-01 21:00
Also make sure that you have libtool and do either glibtoolize or libtoolize.

**Closed by shiozaki** 2018-08-01 20:59 UTC

**Comment by aerask** [comment] 2018-08-02 18:58
I've made sure we have those packages but we're still hitting an error. Most likely case is that the compile test is not correct (line below). When configure runs, it uses boost's include directory while it needs the -I (capital i) argument. One of two things, test needs to exclude boost include directory or it needs to prefix it with -I. 

configure:3459: icc /export/apps/Boost/1.64.0/include conftest.c >&5
/export/apps/Boost/1.64.0/include: file not recognized: Is a directory

**Comment by aerask** [comment] 2018-08-02 19:01
Also, just to mention, we're trying to compile this on CentOS s6, not mac, in case that helps.

**Comment by shiozaki** [comment] 2018-08-02 20:32
Just for your information, this works on our cluster with CentOS6, so it's irrelevant.

On Aug 2, 2018, at 12:01 PM, Alan Rask <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, just to mention, we're trying to compile this on CentOS s6, not mac, in case that helps.

-

**Comment by shiozaki** [comment] 2018-08-03 04:48
This is not to do with -I. The problem is that your autoconf is not recognizing the keyword, which it is supposed to do if you are using a full-feature latest version. Did you check the above link to stackoverflow? BAGEL has been compiled by a few dozen groups, plus automake is reasonably a robust program, so I don’t think there is an issue on our side.

I suggest compiling and installing the newest libtool, autoconf, and automake into your home directory ($HOME/local) without using the package manager and set the path ($PATH, $LD_LIBRARY_PATH, etc) so that the newest ones will be used. It’s trivial.

On Aug 2, 2018, at 1:32 PM, Toru Shiozaki <shiozaki@northwestern.edu<mailto:shiozaki@northwestern.edu>> wrote:

Just for your information, this works on our cluster with CentOS6, so it’s irrelevant.

On Aug 2, 2018, at 12:01 PM, Alan Rask <notifications@github.com<mailto:notifications@github.com>> wrote:


Also, just to mention, we're trying to compile this on CentOS s6, not mac, in case that helps.

**Comment by shiozaki** [comment] 2018-08-07 00:33
GREAT!!! Thanks for letting me know.
